export const exclusions = [
    'https://www.linkedin.com/*',
    'https://*.facebook.com/*',
    // google start
    'https://*.google.com/*',
    'https://*.google.ad/*',
    'https://*.google.ae/*',
    'https://*.google.com.af/*',
    'https://*.google.com.ag/*',
    'https://*.google.com.ai/*',
    'https://*.google.al/*',
    'https://*.google.am/*',
    'https://*.google.co.ao/*',
    'https://*.google.com.ar/*',
    'https://*.google.as/*',
    'https://*.google.at/*',
    'https://*.google.com.au/*',
    'https://*.google.az/*',
    'https://*.google.ba/*',
    'https://*.google.com.bd/*',
    'https://*.google.be/*',
    'https://*.google.bf/*',
    'https://*.google.bg/*',
    'https://*.google.com.bh/*',
    'https://*.google.bi/*',
    'https://*.google.bj/*',
    'https://*.google.com.bn/*',
    'https://*.google.com.bo/*',
    'https://*.google.com.br/*',
    'https://*.google.bs/*',
    'https://*.google.bt/*',
    'https://*.google.co.bw/*',
    'https://*.google.by/*',
    'https://*.google.com.bz/*',
    'https://*.google.ca/*',
    'https://*.google.cd/*',
    'https://*.google.cf/*',
    'https://*.google.cg/*',
    'https://*.google.ch/*',
    'https://*.google.ci/*',
    'https://*.google.co.ck/*',
    'https://*.google.cl/*',
    'https://*.google.cm/*',
    'https://*.google.cn/*',
    'https://*.google.com.co/*',
    'https://*.google.co.cr/*',
    'https://*.google.com.cu/*',
    'https://*.google.cv/*',
    'https://*.google.com.cy/*',
    'https://*.google.cz/*',
    'https://*.google.de/*',
    'https://*.google.dj/*',
    'https://*.google.dk/*',
    'https://*.google.dm/*',
    'https://*.google.com.do/*',
    'https://*.google.dz/*',
    'https://*.google.com.ec/*',
    'https://*.google.ee/*',
    'https://*.google.com.eg/*',
    'https://*.google.es/*',
    'https://*.google.com.et/*',
    'https://*.google.fi/*',
    'https://*.google.com.fj/*',
    'https://*.google.fm/*',
    'https://*.google.fr/*',
    'https://*.google.ga/*',
    'https://*.google.ge/*',
    'https://*.google.gg/*',
    'https://*.google.com.gh/*',
    'https://*.google.com.gi/*',
    'https://*.google.gl/*',
    'https://*.google.gm/*',
    'https://*.google.gp/*',
    'https://*.google.gr/*',
    'https://*.google.com.gt/*',
    'https://*.google.gy/*',
    'https://*.google.com.hk/*',
    'https://*.google.hn/*',
    'https://*.google.hr/*',
    'https://*.google.ht/*',
    'https://*.google.hu/*',
    'https://*.google.co.id/*',
    'https://*.google.ie/*',
    'https://*.google.co.il/*',
    'https://*.google.im/*',
    'https://*.google.co.in/*',
    'https://*.google.iq/*',
    'https://*.google.is/*',
    'https://*.google.it/*',
    'https://*.google.je/*',
    'https://*.google.com.jm/*',
    'https://*.google.jo/*',
    'https://*.google.co.jp/*',
    'https://*.google.co.ke/*',
    'https://*.google.com.kh/*',
    'https://*.google.ki/*',
    'https://*.google.kg/*',
    'https://*.google.co.kr/*',
    'https://*.google.com.kw/*',
    'https://*.google.kz/*',
    'https://*.google.la/*',
    'https://*.google.com.lb/*',
    'https://*.google.li/*',
    'https://*.google.lk/*',
    'https://*.google.co.ls/*',
    'https://*.google.lt/*',
    'https://*.google.lu/*',
    'https://*.google.lv/*',
    'https://*.google.com.ly/*',
    'https://*.google.co.ma/*',
    'https://*.google.md/*',
    'https://*.google.me/*',
    'https://*.google.mg/*',
    'https://*.google.mk/*',
    'https://*.google.ml/*',
    'https://*.google.com.mm/*',
    'https://*.google.mn/*',
    'https://*.google.ms/*',
    'https://*.google.com.mt/*',
    'https://*.google.mu/*',
    'https://*.google.mv/*',
    'https://*.google.mw/*',
    'https://*.google.com.mx/*',
    'https://*.google.com.my/*',
    'https://*.google.co.mz/*',
    'https://*.google.com.na/*',
    'https://*.google.com.nf/*',
    'https://*.google.com.ng/*',
    'https://*.google.com.ni/*',
    'https://*.google.ne/*',
    'https://*.google.nl/*',
    'https://*.google.no/*',
    'https://*.google.com.np/*',
    'https://*.google.nr/*',
    'https://*.google.nu/*',
    'https://*.google.co.nz/*',
    'https://*.google.com.om/*',
    'https://*.google.com.pa/*',
    'https://*.google.com.pe/*',
    'https://*.google.com.pg/*',
    'https://*.google.com.ph/*',
    'https://*.google.com.pk/*',
    'https://*.google.pl/*',
    'https://*.google.pn/*',
    'https://*.google.com.pr/*',
    'https://*.google.ps/*',
    'https://*.google.pt/*',
    'https://*.google.com.py/*',
    'https://*.google.com.qa/*',
    'https://*.google.ro/*',
    'https://*.google.ru/*',
    'https://*.google.rw/*',
    'https://*.google.com.sa/*',
    'https://*.google.com.sb/*',
    'https://*.google.sc/*',
    'https://*.google.se/*',
    'https://*.google.com.sg/*',
    'https://*.google.sh/*',
    'https://*.google.si/*',
    'https://*.google.sk/*',
    'https://*.google.com.sl/*',
    'https://*.google.sn/*',
    'https://*.google.so/*',
    'https://*.google.sm/*',
    'https://*.google.sr/*',
    'https://*.google.st/*',
    'https://*.google.com.sv/*',
    'https://*.google.td/*',
    'https://*.google.tg/*',
    'https://*.google.co.th/*',
    'https://*.google.com.tj/*',
    'https://*.google.tk/*',
    'https://*.google.tl/*',
    'https://*.google.tm/*',
    'https://*.google.tn/*',
    'https://*.google.to/*',
    'https://*.google.com.tr/*',
    'https://*.google.tt/*',
    'https://*.google.com.tw/*',
    'https://*.google.co.tz/*',
    'https://*.google.com.ua/*',
    'https://*.google.co.ug/*',
    'https://*.google.co.uk/*',
    'https://*.google.com.uy/*',
    'https://*.google.co.uz/*',
    'https://*.google.com.vc/*',
    'https://*.google.co.ve/*',
    'https://*.google.vg/*',
    'https://*.google.co.vi/*',
    'https://*.google.com.vn/*',
    'https://*.google.vu/*',
    'https://*.google.ws/*',
    'https://*.google.rs/*',
    'https://*.google.co.za/*',
    'https://*.google.co.zm/*',
    'https://*.google.co.zw/*',
    'https://*.google.cat/*',
    // google end
    'https://*.youtube.com/*',
    '*://disqus.com/embed/*',
    'https://vk.com/*',
    'https://*.vk.com/*',
    'https://vimeo.com/*',
    'https://*.vimeo.com/*',
    '*://*.coub.com/*',
    '*://coub.com/*',
    '*://*.googlesyndication.com/*',
    '*://*.naver.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/227
    'https://gstatic.com/*',
    'https://*.gstatic.com/*',
    // yandex start
    'https://yandex.ru/*',
    'https://*.yandex.ru/*',
    'https://yandex.ua/*',
    'https://*.yandex.ua/*',
    'https://yandex.by/*',
    'https://*.yandex.by/*',
    'https://yandex.com/*',
    'https://*.yandex.com/*',
    'https://yandex.com.tr/*',
    'https://*.yandex.com.tr/*',
    'https://yandex.kz/*',
    'https://*.yandex.kz/*',
    'https://yandex.fr/*',
    'https://*.yandex.fr/*',
    // yandex end
    'https://*.twitch.tv/*',
    'https://tinder.com/*',
    '*://*.yahoo.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/86
    '*://chatovod.ru/*',
    '*://*.chatovod.ru/*',
    '*://vc.ru/*',
    '*://tjournal.ru/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/94
    '*://amanice.ru/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/109
    '*://ka-union.ru/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/122
    '*://gameforge.com/*',
    '*://*.gameforge.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/144
    '*://*.ssgdfm.com/*',
    // https://github.com/AdguardTeam/CoreLibs/issues/490
    '*://*.brainpop.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/149
    '*://*.taobao.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/151
    '*://*.ksl.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/152
    '*://*.t-online.de/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/154
    '*://boards.4channel.org/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/170
    '*://*.washingtonpost.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/157
    '*://*.kakao.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/165
    '*://*.discounttire.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/169
    '*://mail.ukr.net/*',
    '*://*.mail.ukr.net/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/166
    '*://*.sahadan.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/186
    '*://*.groupon.*/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/162
    '*://*.amoma.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/183
    '*://*.jccsmart.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/225
    '*://wp.pl/*',
    '*://*.wp.pl/*',
    '*://money.pl/*',
    '*://*.money.pl/*',
    '*://o2.pl/*',
    '*://*.o2.pl/*',
    '*://pudelek.pl/*',
    '*://*.pudelek.pl/*',
    '*://komorkomania.pl/*',
    '*://*.komorkomania.pl/*',
    '*://gadzetomania.pl/*',
    '*://*.gadzetomania.pl/*',
    '*://fotoblogia.pl/*',
    '*://*.fotoblogia.pl/*',
    '*://autokult.pl/*',
    '*://*.autokult.pl/*',
    '*://abczdrowie.pl/*',
    '*://*.abczdrowie.pl/*',
    '*://parenting.pl/*',
    '*://*.parenting.pl/*',
    '*://dobreprogramy.pl/*',
    '*://*.dobreprogramy.pl/*',
    '*://polygamia.pl/*',
    '*://*.polygamia.pl/*',
    // False positives on myschool.mosreg.ru
    '*://*.mosreg.ru/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/191
    '*://vietjetair.com/*',
    '*://*.vietjetair.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/193
    'https://web.skype.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/197
    '*://karelia.press/*',
    '*://*.karelia.press/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/206
    '*://microsoft.com/*',
    '*://*.microsoft.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/204
    '*://bancoctt.pt/*',
    '*://*.bancoctt.pt/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/203
    '*://print24.com/*',
    '*://*.print24.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/202
    '*://shellfcu.org/*',
    '*://*.shellfcu.org/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/201
    '*://yesfile.com/*',
    '*://*.yesfile.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/200
    '*://sunrise.ch/*',
    '*://*.sunrise.ch/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/208
    '*://cetesdirecto.com/*',
    '*://*.cetesdirecto.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/211
    '*://ubi.com/*',
    '*://*.ubi.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/222
    '*://*.sistic.com.sg/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/224
    '*://*.ilfattoquotidiano.it/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/215
    '*://*.vanis.io/*',
    '*://*.senpa.io/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/236
    '*://wielkopolskiebilety.pl/*',
    '*://*.wielkopolskiebilety.pl/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/210
    '*://*.astrogo.astro.com.my/*',
    '*://*.chaturbate.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/233
    '*://play.pl/*',
    '*://*.play.pl/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/214
    '*://web.de/*',
    '*://*.web.de/*',
    '*://gmx.net/*',
    '*://*.gmx.net/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/234
    '*://clashofclans.com/*',
    '*://*.clashofclans.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/238
    '*://online.bfgruppe.de/*',
    '*://*.online.bfgruppe.de/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/237
    '*://portalpasazera.pl/*',
    '*://*.portalpasazera.pl/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/246
    '*://jeanne-laffitte.com/*',
    '*://*.jeanne-laffitte.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/241
    '*://epicgames.com/*',
    '*://*.epicgames.com/*',
    // https://github.com/AdguardTeam/AdguardFilters/issues/90068
    '*://freizeithugl.de/*',
    '*://*.freizeithugl.de/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/253
    '*://koleje-wielkopolskie.com.pl/*',
    '*://*.koleje-wielkopolskie.com.pl/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/249
    '*://ygosu.com/*',
    '*://*.ygosu.com/*',
    '*://ppss.kr/*',
    '*://*.ppss.kr/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/251
    '*://nordea.com/*',
    '*://*.nordea.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/255
    '*://*.gov/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/257
    '*://austintestingandtherapy.com/*',
    '*://*.austintestingandtherapy.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/254
    '*://learn-anything.xyz/*',
    '*://*.learn-anything.xyz/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/262
    '*://egybest.*/*',
    '*://*.egybest.*/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/263
    '*://ancestry.com/*',
    '*://*.ancestry.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/267
    '*://login.mts.ru/*',
    '*://*.login.mts.ru/*',
    '*://ebay.com/*',
    '*://*.ebay.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/269
    '*://outlook.live.*/*',
    '*://*.outlook.live.*/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/280
    '*://joom.com.*/*',
    '*://*.joom.com.*/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/281
    '*://unrealengine.com/*',
    '*://*.unrealengine.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/283
    'freelancer.com',
    // https://github.com/AdguardTeam/PopupBlocker/issues/278
    'ov-chipkaart.nl',
    // https://github.com/AdguardTeam/PopupBlocker/issues/275
    'tezgoal.com',
    // https://github.com/AdguardTeam/PopupBlocker/issues/280
    'joom.com',
    // https://github.com/AdguardTeam/AdguardFilters/issues/162029
    '*://id.gov.ua/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/297
    '*://github.com/*',
    // https://github.com/AdguardTeam/PopupBlocker/issues/316
    'https://ygosu.com/*',
    'https://m.ygosu.com/*',
    'https://ad-shield.io/*',
    'https://feedclick.net/*',
    'https://sportalkorea.com/*',
    'https://*.sportalkorea.com/*',
    'https://enetnews.co.kr/*',
    'https://*.enetnews.co.kr/*',
    'https://edaily.co.kr/*',
    'https://*.edaily.co.kr/*',
    'https://economist.co.kr/*',
    'https://*.economist.co.kr/*',
    'https://etoday.co.kr/*',
    'https://*.etoday.co.kr/*',
    'https://hankyung.com/*',
    'https://*.hankyung.com/*',
    'https://isplus.com/*',
    'https://*.isplus.com/*',
    'https://hometownstation.com/*',
    'https://*.hometownstation.com/*',
    'https://inven.co.kr/*',
    'https://*.inven.co.kr/*',
    'https://loawa.com/*',
    'https://*.loawa.com/*',
    'https://viva100.com/*',
    'https://*.viva100.com/*',
    'https://joongdo.co.kr/*',
    'https://*.joongdo.co.kr/*',
    'https://kagit.kr/*',
    'https://*.kagit.kr/*',
    'https://jjang0u.com/*',
    'https://*.jjang0u.com/*',
    'https://cboard.net/*',
    'https://*.cboard.net/*',
    'https://interfootball.co.kr/*',
    'https://*.interfootball.co.kr/*',
    'https://fourfourtwo.co.kr/*',
    'https://*.fourfourtwo.co.kr/*',
    'https://newdaily.co.kr/*',
    'https://*.newdaily.co.kr/*',
    'https://genshinlab.com/*',
    'https://*.genshinlab.com/*',
    'https://thephoblographer.com/*',
    'https://*.thephoblographer.com/*',
    'https://dogdrip.net/*',
    'https://*.dogdrip.net/*',
    'https://honkailab.com/*',
    'https://*.honkailab.com/*',
    'https://warcraftrumbledeck.com/*',
    'https://*.warcraftrumbledeck.com/*',
    'https://mlbpark.donga.com/*',
    'https://*.mlbpark.donga.com/*',
    'https://gamingdeputy.com/*',
    'https://*.gamingdeputy.com/*',
    'https://thestockmarketwatch.com/*',
    'https://*.thestockmarketwatch.com/*',
    'https://thesaurus.net/*',
    'https://*.thesaurus.net/*',
    'https://forexlive.com/*',
    'https://*.forexlive.com/*',
    'https://tweaksforgeeks.com/*',
    'https://*.tweaksforgeeks.com/*',
    'https://alle-tests.nl/*',
    'https://*.alle-tests.nl/*',
    'https://allthetests.com/*',
    'https://*.allthetests.com/*',
    'https://issuya.com/*',
    'https://*.issuya.com/*',
    'https://maketecheasier.com/*',
    'https://*.maketecheasier.com/*',
    'https://motorbikecatalog.com/*',
    'https://*.motorbikecatalog.com/*',
    'https://automobile-catalog.com/*',
    'https://*.automobile-catalog.com/*',
    'https://topstarnews.net/*',
    'https://*.topstarnews.net/*',
    'https://worldhistory.org/*',
    'https://*.worldhistory.org/*',
    'https://etnews.com/*',
    'https://*.etnews.com/*',
    'https://iusm.co.kr/*',
    'https://*.iusm.co.kr/*',
    'https://etoland.co.kr/*',
    'https://*.etoland.co.kr/*',
    'https://apkmirror.com/*',
    'https://*.apkmirror.com/*',
    'https://uttranews.com/*',
    'https://*.uttranews.com/*',
    'https://fntimes.com/*',
    'https://*.fntimes.com/*',
    'https://javatpoint.com/*',
    'https://*.javatpoint.com/*',
    'https://text-compare.com/*',
    'https://*.text-compare.com/*',
    'https://vipotv.com/*',
    'https://*.vipotv.com/*',
    'https://lamire.jp/*',
    'https://*.lamire.jp/*',
    'https://dt.co.kr/*',
    'https://*.dt.co.kr/*',
    'https://g-enews.*/*',
    'https://*.g-enews.*/*',
    'https://allthekingz.com/*',
    'https://*.allthekingz.com/*',
    'https://gadgets360.com/*',
    'https://*.gadgets360.com/*',
    'https://sports.hankooki.com/*',
    'https://*.sports.hankooki.com/*',
    'https://ajunews.com/*',
    'https://*.ajunews.com/*',
    'https://munhwa.com/*',
    'https://*.munhwa.com/*',
    'https://zal.kr/*',
    'https://*.zal.kr/*',
    'https://wfmz.com/*',
    'https://*.wfmz.com/*',
    'https://thestar.co.uk/*',
    'https://*.thestar.co.uk/*',
    'https://yorkshirepost.co.uk/*',
    'https://*.yorkshirepost.co.uk/*',
    'https://mydaily.co.kr/*',
    'https://*.mydaily.co.kr/*',
    'https://raenonx.cc/*',
    'https://*.raenonx.cc/*',
    'https://ndtvprofit.com/*',
    'https://*.ndtvprofit.com/*',
    'https://badmouth1.com/*',
    'https://*.badmouth1.com/*',
    'https://logicieleducatif.fr/*',
    'https://*.logicieleducatif.fr/*',
    'https://taxguru.in/*',
    'https://*.taxguru.in/*',
    'https://islamicfinder.org/*',
    'https://*.islamicfinder.org/*',
    'https://aikatu.jp/*',
    'https://*.aikatu.jp/*',
    'https://secure-signup.net/*',
    'https://*.secure-signup.net/*',
    'https://globalrph.com/*',
    'https://*.globalrph.com/*',
    'https://sportsrec.com/*',
    'https://*.sportsrec.com/*',
    'https://reportera.co.kr/*',
    'https://*.reportera.co.kr/*',
    'https://slobodnadalmacija.hr/*',
    'https://*.slobodnadalmacija.hr/*',
    'https://carscoops.com/*',
    'https://*.carscoops.com/*',
    'https://indiatimes.com/*',
    'https://*.indiatimes.com/*',
    'https://flatpanelshd.com/*',
    'https://*.flatpanelshd.com/*',
    'https://sportsseoul.com/*',
    'https://*.sportsseoul.com/*',
    'https://gloria.hr/*',
    'https://*.gloria.hr/*',
    'https://videogamemods.com/*',
    'https://*.videogamemods.com/*',
    'https://adintrend.tv/*',
    'https://ark-unity.com/*',
    'https://*.ark-unity.com/*',
    'https://cool-style.com.tw/*',
    'https://*.cool-style.com.tw/*',
    'https://dziennik.pl/*',
    'https://*.dziennik.pl/*',
    'https://eurointegration.com.ua/*',
    'https://*.eurointegration.com.ua/*',
    'https://jin115.com/*',
    'https://*.jin115.com/*',
    'https://onlinegdb.com/*',
    'https://*.onlinegdb.com/*',
    'https://winfuture.de/*',
    'https://*.winfuture.de/*',
    'https://hoyme.jp/*',
    'https://*.hoyme.jp/*',
    'https://pravda.com.ua/*',
    'https://*.pravda.com.ua/*',
    'https://freemcserver.net/*',
    'https://*.freemcserver.net/*',
    'https://esuteru.com/*',
    'https://*.esuteru.com/*',
    'https://pressian.com/*',
    'https://*.pressian.com/*',
    'https://blog.livedoor.jp/kinisoku/*',
    'https://blog.livedoor.jp/nanjstu/*',
    'https://itainews.com/*',
    'https://*.itainews.com/*',
    'https://infinityfree.com/*',
    'https://*.infinityfree.com/*',
    'https://wort-suchen.de/*',
    'https://*.wort-suchen.de/*',
    'https://dramabeans.com/*',
    'https://*.dramabeans.com/*',
    'https://word-grabber.com/*',
    'https://*.word-grabber.com/*',
    'https://palabr.as/*',
    'https://*.palabr.as/*',
    'https://motscroises.fr/*',
    'https://*.motscroises.fr/*',
    'https://cruciverba.it/*',
    'https://*.cruciverba.it/*',
    'https://missyusa.com/*',
    'https://*.missyusa.com/*',
    'https://smsonline.cloud/*',
    'https://*.smsonline.cloud/*',
    'https://crosswordsolver.com/*',
    'https://*.crosswordsolver.com/*',
    'https://heureka.cz/*',
    'https://*.heureka.cz/*',
    'https://oradesibiu.ro/*',
    'https://*.oradesibiu.ro/*',
    'https://oeffnungszeitenbuch.de/*',
    'https://*.oeffnungszeitenbuch.de/*',
    'https://the-crossword-solver.com/*',
    'https://*.the-crossword-solver.com/*',
    'https://woxikon.*/*',
    'https://*.woxikon.*/*',
    'https://oraridiapertura24.it/*',
    'https://*.oraridiapertura24.it/*',
    'https://laleggepertutti.it/*',
    'https://*.laleggepertutti.it/*',
    'https://news4vip.livedoor.biz/*',
    'https://onecall2ch.com/*',
    'https://*.onecall2ch.com/*',
    'https://ff14net.2chblog.jp/*',
    'https://ondemandkorea.com/*',
    'https://*.ondemandkorea.com/*',
    'https://economictimes.com/*',
    'https://*.economictimes.com/*',
    'https://mynet.com/*',
    'https://*.mynet.com/*',
    'https://rabitsokuhou.2chblog.jp/*',
    'https://talkwithstranger.com/*',
    'https://*.talkwithstranger.com/*',
    'https://petitfute.com/*',
    'https://*.petitfute.com/*',
    'https://netzwelt.de/*',
    'https://*.netzwelt.de/*',
    'https://convertcase.net/*',
    'https://*.convertcase.net/*',
    'https://picrew.me/*',
    'https://*.picrew.me/*',
    'https://rostercon.com/*',
    'https://*.rostercon.com/*',
    'https://woxikon.de/*',
    'https://*.woxikon.de/*'
];
