---
version: 2
plan:
  project-key: ADGEXT
  key: POPUPBLOCKTESTSPECS
  name: popup blocker - test

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            docker build \
              --file Dockerfile \
              --progress plain \
              --target test-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/userscript.tar.gz"
  artifacts:
    - name: userscript.tar.gz
      location: output/artifacts
      pattern: userscript.tar.gz
      shared: true
      required: true
  requirements:
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
