name: Mirror

description: Mirrors code to the public repo on every push to master.

on:
  push:
    branches:
      - master

# `contents: read` — checkout source repo
# `actions: write` — disable workflows in the public mirror
# `id-token: write` — Octopass token for push to public repo
permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  mirror:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/mirror.yml@master
    with:
      team: extensions
      target_repo: git@github.com:AdguardTeam/PopupBlocker.git
    secrets: inherit
